// CS Subjects addition — static question data for OS, DBMS, CN
// Structured to match the existing question object shape used by QuestionCard

export const CS_SUBJECTS = [
  { key: "OS", label: "OS", fullName: "Operating Systems" },
  { key: "DBMS", label: "DBMS", fullName: "Database Management Systems" },
  { key: "CN", label: "CN", fullName: "Computer Networks" },
];

export const CS_QUESTIONS = {
  OS: [
    {
      id: "cs-os-1",
      text: "What is the difference between a process and a thread?",
      type: "Technical",
      diff: "Medium",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-15",
      upvotes: 42,
    },
    {
      id: "cs-os-2",
      text: "Explain deadlock and the four conditions required for it.",
      type: "Technical",
      diff: "Hard",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-14",
      upvotes: 38,
    },
    {
      id: "cs-os-3",
      text: "What is virtual memory and how does paging work?",
      type: "Technical",
      diff: "Medium",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-13",
      upvotes: 35,
    },
    {
      id: "cs-os-4",
      text: "Describe the differences between mutex and semaphore.",
      type: "Technical",
      diff: "Hard",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-12",
      upvotes: 31,
    },
    {
      id: "cs-os-5",
      text: "What is context switching and what overhead does it introduce?",
      type: "Technical",
      diff: "Medium",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-11",
      upvotes: 28,
    },
  ],
  DBMS: [
    {
      id: "cs-dbms-1",
      text: "What are the ACID properties of a transaction?",
      type: "Technical",
      diff: "Medium",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-15",
      upvotes: 45,
    },
    {
      id: "cs-dbms-2",
      text: "Explain the difference between clustered and non-clustered indexes.",
      type: "Technical",
      diff: "Medium",
      job: "Database Engineer",
      company: "CS Fundamentals",
      date: "2026-04-14",
      upvotes: 39,
    },
    {
      id: "cs-dbms-3",
      text: "What is normalization? Explain 1NF, 2NF, and 3NF with examples.",
      type: "Technical",
      diff: "Hard",
      job: "Database Engineer",
      company: "CS Fundamentals",
      date: "2026-04-13",
      upvotes: 41,
    },
    {
      id: "cs-dbms-4",
      text: "What is the difference between INNER JOIN and LEFT JOIN?",
      type: "Technical",
      diff: "Easy",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-12",
      upvotes: 50,
    },
    {
      id: "cs-dbms-5",
      text: "Explain the CAP theorem and give a real-world example.",
      type: "Technical",
      diff: "Hard",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-11",
      upvotes: 36,
    },
  ],
  CN: [
    {
      id: "cs-cn-1",
      text: "What is the OSI model? Describe each layer briefly.",
      type: "Technical",
      diff: "Medium",
      job: "Network Engineer",
      company: "CS Fundamentals",
      date: "2026-04-15",
      upvotes: 44,
    },
    {
      id: "cs-cn-2",
      text: "Explain the difference between TCP and UDP.",
      type: "Technical",
      diff: "Easy",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-14",
      upvotes: 48,
    },
    {
      id: "cs-cn-3",
      text: "What is subnetting and why is it used?",
      type: "Technical",
      diff: "Medium",
      job: "Network Engineer",
      company: "CS Fundamentals",
      date: "2026-04-13",
      upvotes: 33,
    },
    {
      id: "cs-cn-4",
      text: "How does DNS resolution work end to end?",
      type: "Technical",
      diff: "Hard",
      job: "Software Engineer",
      company: "CS Fundamentals",
      date: "2026-04-12",
      upvotes: 37,
    },
    {
      id: "cs-cn-5",
      text: "What is the difference between a hub, switch, and router?",
      type: "Technical",
      diff: "Easy",
      job: "Network Engineer",
      company: "CS Fundamentals",
      date: "2026-04-11",
      upvotes: 52,
    },
  ],
};
