// CS Subjects addition — static question data for OS, DBMS, CN, Java & DSA
// Structured to match the existing question object shape used by QuestionCard

export const CS_SUBJECTS = [
  { key: "OS", label: "OS", fullName: "Operating Systems" },
  { key: "DBMS", label: "DBMS", fullName: "Database Management Systems" },
  { key: "CN", label: "CN", fullName: "Computer Networks" },
  // Java & DSA addition
  { key: "JAVA_DSA", label: "Java & DSA", fullName: "Java & Data Structures" },
];

export const CS_QUESTIONS = {
  OS: [
    { id: "cs-os-1", text: "What is an Operating System and why is it used?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 45 },
    { id: "cs-os-2", text: "What is Thrashing?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 32 },
    { id: "cs-os-3", text: "What are the differences between process and thread?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 68 },
    { id: "cs-os-4", text: "What is paging and why do we need it? What is demand paging?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 41 },
    { id: "cs-os-5", text: "What are the different Scheduling Algorithms?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 39 },
    { id: "cs-os-6", text: "What is the difference between logical and physical memory?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 27 },
    { id: "cs-os-7", text: "What is Belady's Anomaly?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 53 },
    { id: "cs-os-8", text: "What is Banker's Algorithm?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 48 },
    { id: "cs-os-9", text: "What is Fragmentation? What are the different types of Fragmentation?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 36 },
    { id: "cs-os-10", text: "What is Spooling?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 21 },
    { id: "cs-os-11", text: "What are the Classic Synchronization Problems?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 42 },
    { id: "cs-os-12", text: "What is the difference between Multitasking and Multiprocessing?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 35 },
    { id: "cs-os-13", text: "What is Starvation and Aging in OS?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 29 },
    { id: "cs-os-14", text: "What is Semaphore and Mutex?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 82 },
    { id: "cs-os-15", text: "What is RAID? What are the different RAID levels?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 44 },
    { id: "cs-os-16", text: "Explain Address Binding. What are the different types of Address Binding?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 31 },
    { id: "cs-os-17", text: "What is cache?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 25 },
    { id: "cs-os-18", text: "What are the different kinds of operations possible on semaphore?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 33 },
    { id: "cs-os-19", text: "Explain zombie process?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 47 },
    { id: "cs-os-20", text: "What is a process? What are the different states of a process?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 56 },
    { id: "cs-os-21", text: "What is a deadlock in OS? What are the necessary conditions for a deadlock?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 71 },
    { id: "cs-os-22", text: "What is difference between Kernel and OS?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 38 },
  ],
  DBMS: [
    { id: "cs-dbms-23", text: "What is DBMS? What are the advantages of DBMS over traditional file-based systems?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 40 },
    { id: "cs-dbms-24", text: "What is RDBMS and what are the advantages?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 34 },
    { id: "cs-dbms-25", text: "What is the difference between Horizontal and Vertical Scaling?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 85 },
    { id: "cs-dbms-26", text: "What are different types of keys in DBMS?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 52 },
    { id: "cs-dbms-27", text: "What are the difference between DDL, DML, and DCL in SQL?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 46 },
    { id: "cs-dbms-28", text: "What is a Transaction? What are ACID properties?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 91 },
    { id: "cs-dbms-29", text: "What is Normalization? What are the different types of normalization?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 76 },
    { id: "cs-dbms-30", text: "What is Denormalization?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 39 },
    { id: "cs-dbms-31", text: "What is Concurrency Control Protocol (CCP)?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 43 },
    { id: "cs-dbms-32", text: "Explain ER-Model?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 28 },
    { id: "cs-dbms-33", text: "What is a JOIN? What are the different types of JOIN?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 89 },
    { id: "cs-dbms-34", text: "What is Data Abstraction? What are the different levels of data abstraction?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 31 },
    { id: "cs-dbms-35", text: "What are the differences between DROP, TRUNCATE and DELETE commands?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 62 },
    { id: "cs-dbms-36", text: "Explain Entity, Entity Type, and Entity Set in DBMS?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 24 },
    { id: "cs-dbms-37", text: "What are the different types of relationships in the DBMS?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 35 },
    { id: "cs-dbms-38", text: "What is lock? What is the difference between shared lock and exclusive lock?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 41 },
    { id: "cs-dbms-39", text: "What are aggregate functions in SQL?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 29 },
    { id: "cs-dbms-40", text: "What is the difference between UNION and UNION ALL?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 58 },
  ],
  CN: [
    { id: "cs-cn-41", text: "What is Network? What are the types of Networks (LAN, WAN, MAN)?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 33 },
    { id: "cs-cn-42", text: "What is Network Topology? What are the types of Network Topology?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 27 },
    { id: "cs-cn-43", text: "What is TCP Model?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 44 },
    { id: "cs-cn-44", text: "What is OSI Model? What are the different layers of OSI Model?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 81 },
    { id: "cs-cn-45", text: "What is the difference between OSI and TCP Model?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 59 },
    { id: "cs-cn-46", text: "What is the difference between gateway and router?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 42 },
    { id: "cs-cn-47", text: "What is MAC Address?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 26 },
    { id: "cs-cn-48", text: "What is the difference between hub and switch?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 63 },
    { id: "cs-cn-49", text: "What is the difference between IPv4 and IPv6 Protocols?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 51 },
    { id: "cs-cn-50", text: "Explain the concept of IP addressing and subnetting.", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 68 },
    { id: "cs-cn-51", text: "What is 3-Way Handshaking?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 75 },
    { id: "cs-cn-52", text: "What is HTTP and HTTPS protocol?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 49 },
    { id: "cs-cn-53", text: "What are the differences between TCP and UDP protocols?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 94 },
    { id: "cs-cn-54", text: "What are the different types of delays?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 38 },
    { id: "cs-cn-55", text: "What is VPN? What are the advantages and disadvantages of VPN?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 55 },
    { id: "cs-cn-56", text: "What does ping command do?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 32 },
    { id: "cs-cn-57", text: "What is the SMTP Protocol?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 29 },
    { id: "cs-cn-58", text: "What happens when you enter \"google.com\"?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 88 },
    { id: "cs-cn-59", text: "What is an IPv4 address? What are the different classes of IPv4?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-06", upvotes: 43 },
    { id: "cs-cn-60", text: "What is DNS?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-06", upvotes: 61 },
  ],
  // Java & DSA addition — empty array, questions coming soon
  JAVA_DSA: [],
};

// Java & DSA addition — topic groups for empty-state UI
export const JAVA_DSA_TOPICS = [
  { key: "java-basics", label: "Java Basics", icon: "☕", description: "OOP, JVM, syntax, and core language features" },
  { key: "arrays", label: "Arrays", icon: "📊", description: "Traversal, manipulation, and common patterns" },
  { key: "strings", label: "Strings", icon: "🔤", description: "String operations, regex, and builder patterns" },
  { key: "linked-list", label: "Linked List", icon: "🔗", description: "Singly, doubly, and circular linked lists" },
  { key: "stack-queue", label: "Stack & Queue", icon: "📚", description: "LIFO/FIFO structures, deque, and priority queues" },
  { key: "recursion", label: "Recursion", icon: "🔄", description: "Base cases, backtracking, and memoization" },
  { key: "trees", label: "Trees", icon: "🌳", description: "BST, AVL, traversals, and tree-based problems" },
  { key: "sorting-searching", label: "Sorting & Searching", icon: "🔍", description: "Classic algorithms and binary search variants" },
];
