// CS Subjects addition — static question data for OS, DBMS, CN, Java & DSA
// Structured to match the existing question object shape used by QuestionCard

export const CS_SUBJECTS = [
  { key: "OS", label: "OS", fullName: "Operating Systems" },
  { key: "DBMS", label: "DBMS", fullName: "Database Management Systems" },
  { key: "CN", label: "CN", fullName: "Computer Networks" },
  // Java & DSA addition
  { key: "JAVA_DSA", label: "Java & DSA", fullName: "Java & Data Structures" },
];

export const CS_QUESTIONS = {
  OS: [
    { id: "cs-os-1", text: "What is an Operating System and why is it used?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 45 },
    { id: "cs-os-2", text: "What is Thrashing?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 32 },
    { id: "cs-os-3", text: "What are the differences between process and thread?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 68 },
    { id: "cs-os-4", text: "What is paging and why do we need it? What is demand paging?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 41 },
    { id: "cs-os-5", text: "What are the different Scheduling Algorithms?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 39 },
    { id: "cs-os-6", text: "What is the difference between logical and physical memory?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 27 },
    { id: "cs-os-7", text: "What is Belady's Anomaly?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 53 },
    { id: "cs-os-8", text: "What is Banker's Algorithm?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 48 },
    { id: "cs-os-9", text: "What is Fragmentation? What are the different types of Fragmentation?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 36 },
    { id: "cs-os-10", text: "What is Spooling?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 21 },
    { id: "cs-os-11", text: "What are the Classic Synchronization Problems?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 42 },
    { id: "cs-os-12", text: "What is the difference between Multitasking and Multiprocessing?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 35 },
    { id: "cs-os-13", text: "What is Starvation and Aging in OS?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 29 },
    { id: "cs-os-14", text: "What is Semaphore and Mutex?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 82 },
    { id: "cs-os-15", text: "What is RAID? What are the different RAID levels?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 44 },
    { id: "cs-os-16", text: "Explain Address Binding. What are the different types of Address Binding?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 31 },
    { id: "cs-os-17", text: "What is cache?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 25 },
    { id: "cs-os-18", text: "What are the different kinds of operations possible on semaphore?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 33 },
    { id: "cs-os-19", text: "Explain zombie process?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 47 },
    { id: "cs-os-20", text: "What is a process? What are the different states of a process?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 56 },
    { id: "cs-os-21", text: "What is a deadlock in OS? What are the necessary conditions for a deadlock?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 71 },
    { id: "cs-os-22", text: "What is difference between Kernel and OS?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 38 },
  ],
  DBMS: [
    { id: "cs-dbms-23", text: "What is DBMS? What are the advantages of DBMS over traditional file-based systems?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 40 },
    { id: "cs-dbms-24", text: "What is RDBMS and what are the advantages?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 34 },
    { id: "cs-dbms-25", text: "What is the difference between Horizontal and Vertical Scaling?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 85 },
    { id: "cs-dbms-26", text: "What are different types of keys in DBMS?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 52 },
    { id: "cs-dbms-27", text: "What are the difference between DDL, DML, and DCL in SQL?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 46 },
    { id: "cs-dbms-28", text: "What is a Transaction? What are ACID properties?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 91 },
    { id: "cs-dbms-29", text: "What is Normalization? What are the different types of normalization?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 76 },
    { id: "cs-dbms-30", text: "What is Denormalization?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 39 },
    { id: "cs-dbms-31", text: "What is Concurrency Control Protocol (CCP)?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 43 },
    { id: "cs-dbms-32", text: "Explain ER-Model?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 28 },
    { id: "cs-dbms-33", text: "What is a JOIN? What are the different types of JOIN?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 89 },
    { id: "cs-dbms-34", text: "What is Data Abstraction? What are the different levels of data abstraction?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 31 },
    { id: "cs-dbms-35", text: "What are the differences between DROP, TRUNCATE and DELETE commands?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 62 },
    { id: "cs-dbms-36", text: "Explain Entity, Entity Type, and Entity Set in DBMS?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 24 },
    { id: "cs-dbms-37", text: "What are the different types of relationships in the DBMS?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 35 },
    { id: "cs-dbms-38", text: "What is lock? What is the difference between shared lock and exclusive lock?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 41 },
    { id: "cs-dbms-39", text: "What are aggregate functions in SQL?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 29 },
    { id: "cs-dbms-40", text: "What is the difference between UNION and UNION ALL?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 58 },
  ],
  CN: [
    { id: "cs-cn-41", text: "What is Network? What are the types of Networks (LAN, WAN, MAN)?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 33 },
    { id: "cs-cn-42", text: "What is Network Topology? What are the types of Network Topology?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 27 },
    { id: "cs-cn-43", text: "What is TCP Model?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 44 },
    { id: "cs-cn-44", text: "What is OSI Model? What are the different layers of OSI Model?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 81 },
    { id: "cs-cn-45", text: "What is the difference between OSI and TCP Model?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 59 },
    { id: "cs-cn-46", text: "What is the difference between gateway and router?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 42 },
    { id: "cs-cn-47", text: "What is MAC Address?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 26 },
    { id: "cs-cn-48", text: "What is the difference between hub and switch?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 63 },
    { id: "cs-cn-49", text: "What is the difference between IPv4 and IPv6 Protocols?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 51 },
    { id: "cs-cn-50", text: "Explain the concept of IP addressing and subnetting.", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 68 },
    { id: "cs-cn-51", text: "What is 3-Way Handshaking?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 75 },
    { id: "cs-cn-52", text: "What is HTTP and HTTPS protocol?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 49 },
    { id: "cs-cn-53", text: "What are the differences between TCP and UDP protocols?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 94 },
    { id: "cs-cn-54", text: "What are the different types of delays?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 38 },
    { id: "cs-cn-55", text: "What is VPN? What are the advantages and disadvantages of VPN?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 55 },
    { id: "cs-cn-56", text: "What does ping command do?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 32 },
    { id: "cs-cn-57", text: "What is the SMTP Protocol?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 29 },
    { id: "cs-cn-58", text: "What happens when you enter \"google.com\"?", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-07", upvotes: 88 },
    { id: "cs-cn-59", text: "What is an IPv4 address? What are the different classes of IPv4?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-06", upvotes: 43 },
    { id: "cs-cn-60", text: "What is DNS?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-06", upvotes: 61 },
  ],
  // Java & DSA — 100 questions across 9 topic groups
  JAVA_DSA: [
    // ── Java Basics (1–10) ──
    { id: "jd-1", text: "What is JVM and how does it work?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 62, topic: "java-basics" },
    { id: "jd-2", text: "Explain the difference between == and .equals() in Java", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 78, topic: "java-basics" },
    { id: "jd-3", text: "What is method overloading?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 45, topic: "java-basics" },
    { id: "jd-4", text: "What is method overriding?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 47, topic: "java-basics" },
    { id: "jd-5", text: "What are access modifiers in Java?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 41, topic: "java-basics" },
    { id: "jd-6", text: "What is an interface in Java?", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 39, topic: "java-basics" },
    { id: "jd-7", text: "Difference between abstract class and interface", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 72, topic: "java-basics" },
    { id: "jd-8", text: "What is garbage collection?", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 55, topic: "java-basics" },
    { id: "jd-9", text: "Explain exception handling in Java", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 48, topic: "java-basics" },
    { id: "jd-10", text: "Difference between ArrayList and LinkedList", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 67, topic: "java-basics" },
    // ── Arrays (11–25) ──
    { id: "jd-11", text: "Find two numbers in an array that add up to a target", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 95, topic: "arrays" },
    { id: "jd-12", text: "Find the maximum subarray sum", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 88, topic: "arrays" },
    { id: "jd-13", text: "Check if array contains duplicates", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 54, topic: "arrays" },
    { id: "jd-14", text: "Move all zeroes to the end of array", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 46, topic: "arrays" },
    { id: "jd-15", text: "Rotate an array by k steps", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 61, topic: "arrays" },
    { id: "jd-16", text: "Find the product of array except self", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 73, topic: "arrays" },
    { id: "jd-17", text: "Find peak element in array", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 42, topic: "arrays" },
    { id: "jd-18", text: "Merge two sorted arrays", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 57, topic: "arrays" },
    { id: "jd-19", text: "Find missing number in array", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 51, topic: "arrays" },
    { id: "jd-20", text: "Find majority element in array", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 63, topic: "arrays" },
    { id: "jd-21", text: "Find second largest element in array", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 38, topic: "arrays" },
    { id: "jd-22", text: "Rearrange array elements alternately", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 34, topic: "arrays" },
    { id: "jd-23", text: "Find intersection of two arrays", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 45, topic: "arrays" },
    { id: "jd-24", text: "Sort an array of 0s, 1s and 2s", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 69, topic: "arrays" },
    { id: "jd-25", text: "Find duplicate number in array", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 58, topic: "arrays" },
    // ── Strings (26–40) ──
    { id: "jd-26", text: "Reverse a string", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 42, topic: "strings" },
    { id: "jd-27", text: "Check if two strings are anagrams", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 56, topic: "strings" },
    { id: "jd-28", text: "Find first unique character in a string", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 48, topic: "strings" },
    { id: "jd-29", text: "Find longest substring without repeating characters", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 87, topic: "strings" },
    { id: "jd-30", text: "Convert string to integer (atoi)", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 53, topic: "strings" },
    { id: "jd-31", text: "Find longest palindromic substring", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 76, topic: "strings" },
    { id: "jd-32", text: "Check if string is palindrome", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 39, topic: "strings" },
    { id: "jd-33", text: "Count frequency of characters in string", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 35, topic: "strings" },
    { id: "jd-34", text: "Remove duplicate characters from string", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 41, topic: "strings" },
    { id: "jd-35", text: "Find common prefix among strings", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 44, topic: "strings" },
    { id: "jd-36", text: "Check if one string is rotation of another", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 50, topic: "strings" },
    { id: "jd-37", text: "Reverse words in a sentence", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 47, topic: "strings" },
    { id: "jd-38", text: "Find all substrings of a string", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-09", upvotes: 33, topic: "strings" },
    { id: "jd-39", text: "Find smallest window containing all characters", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 71, topic: "strings" },
    { id: "jd-40", text: "Group anagrams together", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-08", upvotes: 64, topic: "strings" },
    // ── Linked List (41–50) ──
    { id: "jd-41", text: "Reverse a linked list", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 82, topic: "linked-list" },
    { id: "jd-42", text: "Detect cycle in linked list", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 74, topic: "linked-list" },
    { id: "jd-43", text: "Merge two sorted linked lists", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 59, topic: "linked-list" },
    { id: "jd-44", text: "Remove nth node from end", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 53, topic: "linked-list" },
    { id: "jd-45", text: "Find middle of linked list", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 46, topic: "linked-list" },
    { id: "jd-46", text: "Delete node in linked list", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 38, topic: "linked-list" },
    { id: "jd-47", text: "Check if linked list is palindrome", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 55, topic: "linked-list" },
    { id: "jd-48", text: "Find intersection point of two linked lists", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 49, topic: "linked-list" },
    { id: "jd-49", text: "Flatten a linked list", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 62, topic: "linked-list" },
    { id: "jd-50", text: "Rotate a linked list", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 44, topic: "linked-list" },
    // ── Stack & Queue (51–60) ──
    { id: "jd-51", text: "Valid parentheses problem", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 91, topic: "stack-queue" },
    { id: "jd-52", text: "Implement stack using queue", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 58, topic: "stack-queue" },
    { id: "jd-53", text: "Implement queue using stack", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 56, topic: "stack-queue" },
    { id: "jd-54", text: "Design a min stack", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 63, topic: "stack-queue" },
    { id: "jd-55", text: "Next greater element", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 52, topic: "stack-queue" },
    { id: "jd-56", text: "Sliding window maximum", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 77, topic: "stack-queue" },
    { id: "jd-57", text: "Evaluate postfix expression", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 34, topic: "stack-queue" },
    { id: "jd-58", text: "Check for balanced brackets", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 48, topic: "stack-queue" },
    { id: "jd-59", text: "Implement circular queue", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 41, topic: "stack-queue" },
    { id: "jd-60", text: "Design LRU cache", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 86, topic: "stack-queue" },
    // ── Recursion & Backtracking (61–70) ──
    { id: "jd-61", text: "Find factorial using recursion", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 36, topic: "recursion" },
    { id: "jd-62", text: "Fibonacci using recursion", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 40, topic: "recursion" },
    { id: "jd-63", text: "Generate all subsets", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 58, topic: "recursion" },
    { id: "jd-64", text: "Generate all permutations", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 65, topic: "recursion" },
    { id: "jd-65", text: "Solve N-Queens problem", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 79, topic: "recursion" },
    { id: "jd-66", text: "Combination sum problem", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 61, topic: "recursion" },
    { id: "jd-67", text: "Word search in grid", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 72, topic: "recursion" },
    { id: "jd-68", text: "Palindrome partitioning", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 54, topic: "recursion" },
    { id: "jd-69", text: "Sudoku solver", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 83, topic: "recursion" },
    { id: "jd-70", text: "Tower of Hanoi", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 49, topic: "recursion" },
    // ── Trees (71–80) ──
    { id: "jd-71", text: "Binary tree inorder traversal", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 55, topic: "trees" },
    { id: "jd-72", text: "Preorder traversal of binary tree", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 43, topic: "trees" },
    { id: "jd-73", text: "Postorder traversal of binary tree", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 41, topic: "trees" },
    { id: "jd-74", text: "Maximum depth of binary tree", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 52, topic: "trees" },
    { id: "jd-75", text: "Check if two trees are identical", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 38, topic: "trees" },
    { id: "jd-76", text: "Lowest common ancestor in BST", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 67, topic: "trees" },
    { id: "jd-77", text: "Validate binary search tree", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 71, topic: "trees" },
    { id: "jd-78", text: "Level order traversal", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 60, topic: "trees" },
    { id: "jd-79", text: "Diameter of binary tree", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 56, topic: "trees" },
    { id: "jd-80", text: "Check if tree is balanced", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 48, topic: "trees" },
    // ── Sorting & Searching (81–90) ──
    { id: "jd-81", text: "Binary search implementation", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 64, topic: "sorting-searching" },
    { id: "jd-82", text: "Search in rotated sorted array", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 78, topic: "sorting-searching" },
    { id: "jd-83", text: "Merge intervals", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 72, topic: "sorting-searching" },
    { id: "jd-84", text: "Find kth largest element", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 68, topic: "sorting-searching" },
    { id: "jd-85", text: "Quick sort algorithm", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 59, topic: "sorting-searching" },
    { id: "jd-86", text: "Merge sort algorithm", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 57, topic: "sorting-searching" },
    { id: "jd-87", text: "Count inversions in array", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 52, topic: "sorting-searching" },
    { id: "jd-88", text: "Find median of two sorted arrays", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 84, topic: "sorting-searching" },
    { id: "jd-89", text: "First and last position of element", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 46, topic: "sorting-searching" },
    { id: "jd-90", text: "Search insert position", type: "Technical", diff: "Easy", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 39, topic: "sorting-searching" },
    // ── Mixed / Intermediate DSA (91–100) ──
    { id: "jd-91", text: "Trapping rain water problem", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-15", upvotes: 92, topic: "mixed-dsa" },
    { id: "jd-92", text: "Container with most water", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 79, topic: "mixed-dsa" },
    { id: "jd-93", text: "Longest consecutive sequence", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-14", upvotes: 65, topic: "mixed-dsa" },
    { id: "jd-94", text: "Subarray sum equals k", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 71, topic: "mixed-dsa" },
    { id: "jd-95", text: "Clone a graph", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-13", upvotes: 53, topic: "mixed-dsa" },
    { id: "jd-96", text: "Course schedule problem", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 74, topic: "mixed-dsa" },
    { id: "jd-97", text: "Detect cycle in directed graph", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-12", upvotes: 68, topic: "mixed-dsa" },
    { id: "jd-98", text: "Topological sort", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 61, topic: "mixed-dsa" },
    { id: "jd-99", text: "Number of islands", type: "Technical", diff: "Medium", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-11", upvotes: 85, topic: "mixed-dsa" },
    { id: "jd-100", text: "Word ladder problem", type: "Technical", diff: "Hard", job: "Software Engineer", company: "CS Fundamentals", date: "2026-04-10", upvotes: 70, topic: "mixed-dsa" },
  ],
};

// Java & DSA — topic groups for topic-filter UI
export const JAVA_DSA_TOPICS = [
  { key: "all", label: "All Topics", icon: "📋", description: "All Java & DSA questions" },
  { key: "java-basics", label: "Java Basics", icon: "☕", description: "OOP, JVM, syntax, and core language features" },
  { key: "arrays", label: "Arrays", icon: "📊", description: "Traversal, manipulation, and common patterns" },
  { key: "strings", label: "Strings", icon: "🔤", description: "String operations, regex, and builder patterns" },
  { key: "linked-list", label: "Linked List", icon: "🔗", description: "Singly, doubly, and circular linked lists" },
  { key: "stack-queue", label: "Stack & Queue", icon: "📚", description: "LIFO/FIFO structures, deque, and priority queues" },
  { key: "recursion", label: "Recursion", icon: "🔄", description: "Base cases, backtracking, and memoization" },
  { key: "trees", label: "Trees", icon: "🌳", description: "BST, AVL, traversals, and tree-based problems" },
  { key: "sorting-searching", label: "Sorting & Searching", icon: "🔍", description: "Classic algorithms and binary search variants" },
  { key: "mixed-dsa", label: "Mixed DSA", icon: "🧠", description: "Graph, DP, and intermediate-level problems" },
];
